server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        path: /

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB
      resolve-lazily: on

  application:
    name: Sports Profiles App
  datasource:
    platform: postgres
    continue-on-error: false
    url: jdbc:h2:mem:sports_profile
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 30
          batch_versioned_data: true
        temp:
          use_jdbc_metadata_defaults: false
        order_inserts: true
        order_updates: true
        show_sql: false
        use_sql_comments: false
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default_schema: sports_profile
  flyway:
    enabled: true

sport-profile:
  url: http://localhost:8080/

web:
  url:
    main:
